### PR TITLE
CCMSG-852: Swallow exceptions and continue recovery when attempting to apply a corrupt WAL

### PR DESCRIPTION
**Pull request by BlueEldur**
Mirrored from https://github.com/confluentinc/kafka-connect-hdfs3/pull/50

## Problem
When we throw an IOException when detecting WAL corruption, we end up stopping the recovery and retrying. But since WAL file is still corrupt, the retry will always fail.
This issue has been described in numerous issues 
https://github.com/confluentinc/kafka-connect-hdfs/issues/264
https://github.com/confluentinc/kafka-connect-hdfs/issues/372 

## Solution
We throw a custom exception that is caught later higher up in the FSWAL, logged, and swallowed, such that [recover()](https://github.com/confluentinc/kafka-connect-hdfs3/blob/master/src/main/java/io/confluent/connect/hdfs3/TopicPartitionWriter.java#L252) in the topicPartitionWriter is allowed to continue gracefully.  

##### Does this solution apply anywhere else?
- [] yes
- [x] no

## Test Strategy
Wrote a test that checks the low level behavior of the reader, a test that checks if the recovery process finishes gracefully without applying anything from the corrupt WAL, and a test that checks writing with the TPW after a corrupt recovery.

##### Testing done:
- [x] Unit tests
- [ ] Integration tests
- [ ] System tests
- [ ] Manual tests

## Release Plan

 
backporting to 5.5.x

### CODE REVIEW

**Comment by kkonstantine** [comment]
The description is not publicly available from the `hdfs3` repo. Let's add here too even though the issue is symmetric.

**Comment by BlueEldur** [comment]
> The description is not publicly available from the `hdfs3` repo. Let's add here too even though the issue is symmetric.

This whole time I thought HDFS3 was open source.. will do.

**Review by levzem — APPROVED** [review]
LGTM

**Review by kkonstantine — APPROVED** [review]
LGTM

**Pull request merged**
