### PR TITLE
Fix parquet hive duplicate column

### PR DESCRIPTION
**Pull request by RussWinkler**
Fix an issue where the Parquet Hive Utility would add the partition column as a regular column, then allow hive to create an additional partition column thereby creating a duplicate column for the partition column with the same name and creating an invalid hive table definition.  

Updated the associated tests accordingly.

This is an updated fix for my older submitted issue: https://github.com/confluentinc/kafka-connect-hdfs/issues/238

### CODE REVIEW

**Comment by chromy96** [comment]
@RussWinkler were there any progress on this?

@kkonstantine Would it be possible to get info what checks have failed so we could review the changes?

**Comment by kaushiksrinivas** [comment]
any progress or updates on this ?

**Comment by kaushiksrinivas** [comment]
is this fix still pursued with this PR or should we raise a new PR to take this submission forward ?

**Comment by dosvath** [comment]
Replaced by https://github.com/confluentinc/kafka-connect-hdfs/pull/513

**Pull request closed without merging**
