### PR TITLE
Issue 136 - Support topic with dots in hive.

### PR DESCRIPTION
**Pull request by ig-michaelpearce**
@cotedm replacement PR for https://github.com/confluentinc/kafka-connect-hdfs/pull/137

Fixes Issue #136

### CODE REVIEW

**Comment by cotedm** [comment]
I think this looks good. @ewencp can you double check? I'll close out #137 as it's superceded by this .

**Comment by ewencp** [comment]
ok to test

**Comment by ewencp** [comment]
LGTM, thanks @ig-michaelpearce

**Comment by tegansnyder** [comment]
Hive doesn't appear to like dashes in table names either. Can this modified https://github.com/confluentinc/kafka-connect-hdfs/blob/master/src/main/java/io/confluent/connect/hdfs/hive/HiveMetaStore.java#L358 

Something added like this
```java
table.replaceAll("\\-", "_");
```

**Pull request merged**
