### PR TITLE
Add zero padding of offsets in filenames.

### PR DESCRIPTION
**Pull request by ewencp**

### CODE REVIEW

**Comment by ewencp** [comment]
@Ishiihara

**Comment by Ishiihara** [comment]
LGTM

**Comment by Ishiihara** [comment]
@ewencp Should we check negative values and makes sure the value is integer?

**Comment by ewencp** [comment]
@Ishiihara Good point. The type in the config already ensures it's an integer, I added a validator to ensure it's >= 0.

**Pull request merged**
