### PR TITLE
CC-147: Decimal Logical type support for Hive 

### PR DESCRIPTION
**Pull request by liukrimhrim**
With this PR, `Decimal` logical type will be supported when Hive integration is on. This PR depends on the PR https://github.com/confluentinc/kafka-connect-storage-common/pull/114

### CODE REVIEW

**Comment by liukrimhrim** [comment]
> LGTM, just gotta add those semicolons 😄it will fix the build issue as well

Thanks man! That's a really dumb mistake of mine. It is hard to test with jenkins job, because it depends on another PR on another repo

**Comment by liukrimhrim** [comment]
Retargeted to `5.1.x` because it depends on `avro-converter` `5.1.x` and later.

**Comment by levzem** [comment]
> Is it possible to test this as well?

+1

**Comment by liukrimhrim** [comment]
> > Is it possible to test this as well?
> 
> +1

I have tested with its dependencies. It cannot be tested alone.

**Comment by Vincent-Zeng** [comment]
Hi. When to merge this PR?

**Pull request closed without merging**
