### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by lala7573**
Just fixed a typo.

### CODE REVIEW

**Comment by lala7573** [comment]
[clabot:check]

**Comment by levzem** [comment]
@lala7573 can you please rebase this PR to point at the branch that first introduced this PR?

**Comment by levzem** [comment]
@lala7573 just checked and its `4.0.x`

**Comment by lala7573** [comment]
@levzem Thanks. I updated.

**Review by levzem — APPROVED** [review]
LGTM. thanks @lala7573!

**Pull request merged**
