### PR TITLE
Remove invalid offset check.

### PR DESCRIPTION
**Pull request by ewencp**
This has been fixed since 0.10.1, so it has been long enough to allow for compatibility.

### CODE REVIEW

**Comment by avnerl** [comment]
can someone please explain how to build kafka connect from source?
or explain how can I test commit b3d0a04 in my cluster?
i'm having serious issue with this connector.
i'm using version 3.3.1 in docker on k8s with 6 pods. 
at some point in time it just stopped consuming some of the partitions and printed this:

```
[2017-11-21 17:35:44,937] INFO Got brand-new compressor [.snappy] (org.apache.hadoop.io.compress.CodecPool:153)
[2017-11-21 17:35:45,841] INFO Starting commit and rotation for topic partition myTopic-12 with start offsets {} and end offsets {} (io.confluent.connect.hdfs.TopicPartitionWriter:297)
[2017-11-21 17:35:45,916] INFO Starting commit and rotation for topic partition myTopic-17 with start offsets {} and end offsets {} (io.confluent.connect.hdfs.TopicPartitionWriter:297)
[2017-11-21 17:35:46,683] INFO Starting commit and rotation for topic partition myTopic-16 with start offsets {} and end offsets {} (io.confluent.connect.hdfs.TopicPartitionWriter:297)
[2017-11-21 17:35:46,790] INFO Starting commit and rotation for topic partition myTopic-14 with start offsets {} and end offsets {} (io.confluent.connect.hdfs.TopicPartitionWriter:297)
```

nothing seems to solve this issue but moving the entire topic.dir aside and let the connector create a fresh new one.

thanks!

**Comment by kkonstantine** [comment]
To compile the HDFS Connector from source, read the dependencies you need to also checkout here: https://github.com/confluentinc/kafka-connect-hdfs/wiki/FAQ

After running `mvn clean package` successfully, you'll find the connector's jar along with its dependency jars under `target/kafka-connect-hdfs-<version>-package`

**Comment by avnerl** [comment]
thanks for the quick reply but this wiki is incorrect. 
this is the correct steps for building this from source (i hope i can save someone an afternoon):

```
mkdir -p confluentinc && cd confluentinc
git clone -b 4.0.x https://github.com/confluentinc/common.git
sed -i '' 's|<kafka.version>1.0.0-SNAPSHOT</kafka.version>|<kafka.version>1.0.0</kafka.version>|g' pom.xml
cd common && mvn install
cd parent
git clone -b 4.0.x https://github.com/confluentinc/rest-utils.git
cd rest-utils && mvn install
git clone -b 4.0.x https://github.com/confluentinc/schema-registry.git
cd schema-registry && mvn install
cd ../../
git clone -b 4.0.x https://github.com/confluentinc/kafka-connect-storage-common.git
cd kafka-connect-storage-common && mvn install
git clone -b 4.0.x https://github.com/confluentinc/kafka-connect-hdfs.git
cd kafka-connect-hdfs && mvn install
```

why not making a simple master project with git submodules and a master pom?

**Comment by kkonstantine** [comment]
Interesting that you say it's incorrect. The FAQ lists exactly the dependencies that you use. It doesn't describe the exact steps. These might differ slightly depending on the version you are trying to build. But the dependencies are up-to-date. 

Glad you made it work for you!

**Comment by avnerl** [comment]
the exact dependency list. but in the wrong building order, and without stating that one is a parent of the other and that you can't build kafka 1.0.0-SNAPSHOT from source.
I had to figure all this by myself (trying to test a critical bug here). 
Makefile maybe?

**Comment by kkonstantine** [comment]
Regarding building kafka, what you are attempting is to build is tricky for the following reason: 

The Apache Kafka release for 1.0.0 has taken place (so, no snapshot there). 
The 4.0.0 Confluent Platform release has not. Thus, the common repo is depending on a fork of Kafka repo (found here: https://github.com/confluentinc/kafka) that is still on the snapshot version. (see here: https://github.com/confluentinc/kafka/blob/1.0/gradle.properties) 

The quickest thing to do if you want to build the soon-to-be-released version of a connector, is to checkout Kafka from the above fork. 

I hope this helps.

**Comment by avnerl** [comment]
this is so unfortunate. i got the jars built but the container is crashing. my original containers were built using apt-get. now i have to reverse engineer the apt-get setup.
what is the purpose of not sharing your snapshots and build procedure?
why making the build procedure so complex?
this is unclear to me. the whole purpose of community is us helping you test your code and make it better, doesn't it?

**Comment by avnerl** [comment]
for what it worth i build the confluent platform from source (branch 4.0.x) and the issue is now gone. all data is being processed as excepted. more over, the new time based field partitioner also seems to be working fine. this still in staging tests, but so far looks good.

for those of you who are looking for way to build confluent platform from source - here's the quick and dirty script:

tested on macOS high sierra using:
Oracle JDK 1.8.0-144
gradle 4.3.1
maven 3.5.2
```
#!/usr/bin/env bash

# how to decide which kafka branch/tag to checkout?
# let's say we are about to build confluent 4.0.x
# got to https://github.com/confluentinc/common/blob/4.0.x/pom.xml <-- make sure you're looking at correct confluent branch/tag that you're trying to build!
# look for <kafka.version>1.0.0-SNAPSHOT</kafka.version>
# remember the kafka version number
# now go to https://github.com/confluentinc/kafka/blob/trunk/gradle.properties
# look for version=1.0.0-SNAPSHOT
# if the version in kafka project differs from the version in the common project,
# then look for the right kafka branch/tag that builds 1.0.0-SNAPSHOT
# the kafka branch/tag name is the the version you're looking for.
# in this example, branch 1.0 is going to build kafka 1.0.0-SNAPSHOT

# this build script omits camus and kafka-connect-storage-cloud - you may add'em yourself if you want

KAFKA_TAG=1.0
CONFLUENT_TAG=4.0.x
GRADLE_VERSION=$(gradle --version | awk '/Gradle/ { print $2 }')

#mkdir -p confluentinc && cd confluentinc

echo clonning confluentinc-kafka ${KAFKA_TAG}
git -C kafka pull origin ${KAFKA_TAG} || git clone -b ${KAFKA_TAG} https://github.com/confluentinc/kafka.git
cd kafka
gradle wrapper --gradle-version ${GRADLE_VERSION}
./gradlew clean releaseTarGz -x test
KAFKA_TAR_GZ=$(ls core/build/distributions | grep -v docs)
tar -xvzf core/build/distributions/${KAFKA_TAR_GZ} -C core/build/distributions/
cd ..

echo clonning confluentinc-common ${CONFLUENT_TAG}
git -C common pull origin ${CONFLUENT_TAG} || git clone -b ${CONFLUENT_TAG} https://github.com/confluentinc/common.git
mvn -f common install -DskipTests
cd common/parent

echo clonning confluentinc-kafka-connect-jdbc ${CONFLUENT_TAG}
git -C kafka-connect-jdbc pull origin ${CONFLUENT_TAG} || git clone -b ${CONFLUENT_TAG} https://github.com/confluentinc/kafka-connect-jdbc.git
mvn -f kafka-connect-jdbc clean install -DskipTests

echo clonning confluentinc-kafka-connect-elasticsearch ${CONFLUENT_TAG}
git -C kafka-connect-elasticsearch pull origin ${CONFLUENT_TAG} || git clone -b ${CONFLUENT_TAG} https://github.com/confluentinc/kafka-connect-elasticsearch.git
mvn -f kafka-connect-elasticsearch clean install -DskipTests

echo clonning confluentinc-rest-utils ${CONFLUENT_TAG}
git -C rest-utils pull origin ${CONFLUENT_TAG} || git clone -b ${CONFLUENT_TAG} https://github.com/confluentinc/rest-utils.git
mvn -f rest-utils clean install -DskipTests
cd rest-utils

echo clonning confluentinc-schema-registry ${CONFLUENT_TAG}
git -C schema-registry pull origin ${CONFLUENT_TAG} || git clone -b ${CONFLUENT_TAG} https://github.com/confluentinc/schema-registry.git
mvn -f schema-registry clean install -DskipTests

echo clonning confluentinc-kafka-rest ${CONFLUENT_TAG}
git -C kafka-rest pull origin ${CONFLUENT_TAG} || git clone -b ${CONFLUENT_TAG} https://github.com/confluentinc/kafka-rest.git
mvn -f kafka-rest clean install -DskipTests
cd ../

echo clonning confluentinc-kafka-connect-storage-common ${CONFLUENT_TAG}
git -C kafka-connect-storage-common pull origin ${CONFLUENT_TAG} || git -C kafka pull origin ${CONFLUENT_TAG} ||  git clone -b ${CONFLUENT_TAG} https://github.com/confluentinc/kafka-connect-storage-common.git
mvn -f kafka-connect-storage-common clean install -DskipTests

echo clonning confluentinc-kafka-connect-hdfs ${CONFLUENT_TAG}
git -C kafka-connect-hdfs pull origin ${CONFLUENT_TAG} || git clone -b ${CONFLUENT_TAG} https://github.com/confluentinc/kafka-connect-hdfs.git
mvn -f kafka-connect-hdfs clean install -DskipTests

# get confluent version from common/pom.xml
CONFLUENT_VERSION=$(grep "confluent.version>.*</confluent.version" common/pom.xml | awk -F '[<>]' '/confluent.version/ {print $3}')
OUTPUT_FOLDER=confluent-${CONFLUENT_VERSION}

mkdir -p ${OUTPUT_FOLDER}
# clean previous builds
rm -rf ${OUTPUT_FOLDER}/*

# copy confluent jars
for package in $(find . -name "*-package"); do
  cp -r ${package}/* ${OUTPUT_FOLDER}/
done

# copy kafka jars
mkdir -p ${OUTPUT_FOLDER}/share/java/kafka/
cp -r kafka/core/build/distributions/kafka*/libs/* ${OUTPUT_FOLDER}/share/java/kafka/

# copy kafka config
mkdir -p ${OUTPUT_FOLDER}/etc/kafka
cp kafka/core/build/distributions/kafka*/config/* ${OUTPUT_FOLDER}/etc/kafka

# copy kafka/confluent bin
mkdir -p ${OUTPUT_FOLDER}/bin
# for some reason confluent does not share thier platform sh files
# so the only way to make this work is using previous version bin folder
# if dont have it, go here: https://www.confluent.io/download/ and download the
# open source version and extract its bin folder (in this example it was renamed to bin-3.3.1 <- i.e. previous version)
# cp -r kafka/core/build/distributions/kafka*/bin/* ${OUTPUT_FOLDER}/bin <- this wont work since it is apache kafka bin folder. that is why it is commented out.
find bin-3.3.1/* -not -path "*windows*" -exec cp {} ${OUTPUT_FOLDER}/bin/ \;
# make sure windows folder is not included
rm -rf ${OUTPUT_FOLDER}/bin/windows

# clean previous tar ball if exists
rm -f ${OUTPUT_FOLDER}.tar.gz
# create tar ball
tar -zcvf  ${OUTPUT_FOLDER}.tar.gz  ${OUTPUT_FOLDER}
```

**Pull request merged**
