### PR TITLE
adding support for several partition fields not just one 

### PR DESCRIPTION
**Pull request by doriwal**
public void configure(Map<String, Object> config) {
    fieldName = (String) config.get(HdfsSinkConnectorConfig.PARTITION_FIELD_NAME_CONFIG);
     // adding support to serverl partition fields (split by ',')
    String[] fields = fieldName.split(",");
    for(int i =0; i < fields.length ; i++){
      partitionFields.add(new FieldSchema(fields[i], TypeInfoFactory.stringTypeInfo.toString(), ""));
    }
  }

### CODE REVIEW

**Comment by doriwal** [comment]
In my use case I create parquet file that needs to be partition by several fields : type , day , hour 
those are 3 attributes in my event object , I would like to use kafka connect to read the data from kafka and to write it to parquet, I submit pull request with my code change to support this functionality

**Comment by doriwal** [comment]
where can I sign  Contributor License Agreement ?

**Comment by xianzhen** [comment]
Hi. @doriwal 
Changing the type of "PARTITION_FIELD_NAME_CONFIG" into LIST mybe a better way.
I create this pull request: 
https://github.com/confluentinc/kafka-connect-hdfs/pull/104

**Comment by doriwal** [comment]
Sure . List is the a better way.

Thanks for adding this feature.

**Comment by shikhar** [comment]
Closing this in favor of #104

**Pull request closed without merging**
