### PR TITLE
Supports ORC Format w/Hive

### LINKED ISSUE #173: ORC Format to HDFS
Are there any plans for an ORCFormat (like Parquet and Avro Format) that can be used with the connector to write out Avro Schema styled data into HDFS in ORC format?

### PR DESCRIPTION
**Pull request by cricket007**
Closes #173 

Just putting this here for visibility @buom ; Please let us know the state of your code.

### CODE REVIEW

**Comment by cricket007** [comment]
Not sure I understand the question. It's using `org.apache.hadoop.hive.ql.io.orc.OrcInputFormat`, which is what `STORED AS ORC` in a plain Hive statement would do

**Comment by levzem** [comment]
Hi @cricket007, we are interested in implementing your feature - are you still willing to work on this? If so, let me know and I can leave a review - if not, I will go ahead and takeover this PR

**Comment by cricket007** [comment]
I didn't implement, I only created the PR after seeing the branch for it.

**Comment by iqbalhasnan** [comment]
I'm interested to use this feature, any update on the release? thanks

**Comment by levzem** [comment]
taking over with #484

thank you for your contribution @buom and @cricket007 for pointing it out!

@iqbalhasnan we will work on trying to get this feature into the next CP release.

**Pull request closed without merging**
