### PR TITLE
CCMSG-1202: Use kafka-connect-storage-common:10.1.1.

### PR DESCRIPTION
**Pull request by avocader**
## Problem
The current version doesn't package `jackson-mapper-asl` JAR.

It's included as a transitive `test` dependency only:
```
...
[INFO] +- org.apache.hadoop:hadoop-minicluster:jar:2.10.1:test
[INFO] |  +- org.apache.hadoop:hadoop-common:test-jar:tests:2.10.1:test
[INFO] |  |  +- commons-cli:commons-cli:jar:1.2:compile
[INFO] |  |  +- org.apache.commons:commons-math3:jar:3.1.1:compile
[INFO] |  |  +- xmlenc:xmlenc:jar:0.52:compile
[INFO] |  |  +- commons-net:commons-net:jar:3.1:compile
[INFO] |  |  +- javax.servlet:servlet-api:jar:2.5:compile
[INFO] |  |  +- org.mortbay.jetty:jetty:jar:6.1.26:compile
[INFO] |  |  +- org.mortbay.jetty:jetty-util:jar:6.1.26:compile
[INFO] |  |  +- org.mortbay.jetty:jetty-sslengine:jar:6.1.26:compile
[INFO] |  |  +- javax.servlet.jsp:jsp-api:jar:2.1:runtime
[INFO] |  |  +- com.sun.jersey:jersey-core:jar:1.9:compile
[INFO] |  |  +- com.sun.jersey:jersey-json:jar:1.9:compile
[INFO] |  |  |  +- org.codehaus.jettison:jettison:jar:1.1:compile
[INFO] |  |  |  +- com.sun.xml.bind:jaxb-impl:jar:2.2.3-1:compile
[INFO] |  |  |  +- org.codehaus.jackson:jackson-jaxrs:jar:1.8.3:compile
[INFO] |  |  |  \- org.codehaus.jackson:jackson-xc:jar:1.8.3:compile
[INFO] |  |  +- com.sun.jersey:jersey-server:jar:1.9:compile
[INFO] |  |  |  \- asm:asm:jar:3.1:compile
[INFO] |  |  +- net.java.dev.jets3t:jets3t:jar:0.9.0:compile
[INFO] |  |  |  \- com.jamesmurty.utils:java-xmlbuilder:jar:0.4:compile
[INFO] |  |  +- commons-lang:commons-lang:jar:2.6:compile
[INFO] |  |  +- commons-configuration:commons-configuration:jar:1.6:compile
[INFO] |  |  +- commons-digester:commons-digester:jar:1.8:compile
[INFO] |  |  +- commons-beanutils:commons-beanutils:jar:1.9.4:compile
[INFO] |  |  +- org.codehaus.jackson:jackson-core-asl:jar:1.9.13:compile
[INFO] |  |  +- org.codehaus.jackson:jackson-mapper-asl:jar:1.9.14.jdk17-redhat-00001:compile
...
```

## Solution
Add `jackson-mapper-asl` as a dependency.

##### Does this solution apply anywhere else?
- [ ] yes
- [x] no

## Test Strategy
```
$ mvn clean -DskipTests=true package
...
```
```
$ find . -name "jackson-mapper-asl*.jar"
./target/kafka-connect-hdfs-10.0.7-SNAPSHOT-package/share/java/kafka-connect-hdfs/jackson-mapper-asl-1.9.14.jdk17-redhat-00001.jar
./target/components/packages/confluentinc-kafka-connect-hdfs-10.0.7-SNAPSHOT/confluentinc-kafka-connect-hdfs-10.0.7-SNAPSHOT/lib/jackson-mapper-asl-1.9.14.jdk17-redhat-00001.jar
./target/kafka-connect-hdfs-10.0.7-SNAPSHOT-development/share/java/kafka-connect-hdfs/jackson-mapper-asl-1.9.14.jdk17-redhat-00001.jar
```

##### Testing done:
- [ ] Unit tests
- [ ] Integration tests
- [ ] System tests
- [x] Manual tests

### CODE REVIEW

**Review by ilanjiR — COMMENTED** [review]
I think we fixed this somewhere earlier: https://github.com/confluentinc/kafka-connect-hdfs/commit/6ea2b15558089484111d856c19916dedaa6f49ca

**Comment by avocader** [comment]
@ilanjiR it didn't fix it, since this dependency is not getting packaged.

**Review by ilanjiR — APPROVED** [review]
LGTM

**Comment by sonupillai** [comment]
@avocader Please make sure its tested this time. Thank you for the quick turn around.

**Review by kkonstantine — CHANGES_REQUESTED** [review]
The fact that the dependency is listed with scope `:compile` in the dependency tree tells us that this is not a test dependency, even if the parent has test scope. 

A closer inspection on why this wasn't fixed with the recent fix in storage-common reveals that we have a misalignment of versions of storage-common. 
In the parent pom version we have `10.0.6` that should have the fix. But in the property `kafka.connect.storage.common.version` we set `10.1.0` which is the old version that doesn't bring `jackson-mapper-asl` to the version we need. And that's the version we use to get `kafka-connect-storage-hive` which will bring `jackson-mapper-asl` as a transitive dependency. 

Thus, what we need to do is to release `10.1.1` in storage common and set this both as a parent version here and in `kafka.connect.storage.common.version`. The misalignment seems to have been introduced here: https://github.com/confluentinc/kafka-connect-hdfs/pull/556

**Review by kkonstantine — COMMENTED** [review]
We'll have to fully release storage-common 10.1.1 for the build to work and merge here. Also, any reason not to update the parent version to 10.1.1 as well?

**Review by kkonstantine — APPROVED** [review]
LGTM given that tests pass and the dependency is now present

**Comment by avocader** [comment]
@kkonstantine thanks for a catch!

**Pull request merged**
